nuxt-modules/strapi

lib/plugin.js

Fixes reactivity of $strapi.user on client-side hydratation.

fix: reactivity on hydatation

---

lib/plugin.js

I've changed the way the lodash functions are loaded to only include these 2 functions instead of the full lodash library.
This should reduce the build/vendor size of built nuxt applications when using this module.
This reduces the overall vendor size when building your application.

feat: Tiny change to plugin.js to reduce the size of lodash on build

---

.eslintignore
README.md
docs/content/en/index.md
docs/content/en/proxy.md
docs/content/en/typescript.md
lib/index.d.ts
package.json
yarn.lock

Why? I implemented this changes in a personal project and, after finding them extremely useful, I decided to contribute to the repo to make TypeScript support available out-of-the-box for the library.
Added TypeScript support:
- Now the library has an `index.d.ts` which extends Vue and Context interfaces with [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) to provide typings for the module.
Updated the docs:
- Added a "Usage with TypeScript" page to describe the setup and usage with this new feature;
- Moved "Using a proxy" to the last section of the docs and inserted the TypeScript page at the 7th place;
- Added some lines about TypeScript in the `index.md`.
Dependencies:
- Added `@nuxt/types` in the `devDependencies` to provide the ability to …

feat: added typescript support and updated docs accordingly

---

package.json
yarn.lock

* prevents locking `ufo` at a lower level - which can break Nuxt for npm users
* see https://github.com/nuxt/nuxt.js/issues/8898

fix: upgrade `ufo`

---

docs/content/en/strapi.md

The link https://strapi.io/documentation/v3.x/content-api/parameters.html is broken, it redirects to a 404 page.
I updated it to https://strapi.io/documentation/developer-docs/latest/developer-resources/content-api/content-api.html#api-parameters which seems to be the equivalent new page.
No tests since I just updated the documentation markdown.

fix: broken links to Strapi API parameters page

---

docs/pages/strapi.md

Resolves #154, documents the ability to provide and use GraphQL variables with the Strapi module.
Update the documentation to show the Nuxt Strapi module's GraphQL being compatible with variables using a template literal as well as a GraphQL-tag.

docs: Add GraphQL variables example (#154)

---

src/module.ts

The publicRuntimeConfig is not taken into account and is erased by Strapi default configuration object.

fix: Hotfix publicRuntimeConfig vs Strapi default conf

---

docs/pages/3.usage.md
docs/pages/4.advanced.md
src/runtime/types/index.d.ts

PR to implement the feature proposed in issue #189.
Added the possibility to add custom user fields to the registration payload.
`[field: string]: string | number | boolean | object | Array<string | number | boolean | object>`
The types `string`, `number`, `boolean` and `object` together with the same types as an array should cover all possible fields in Strapi.
I also checked if the register endpoint can somehow handle FormData (spoiler, it doesn't) to add a profile picture on registration. But since this would be a custom change to a Strapi controller, it's not really needed here.
Furthermore I added the `cas` authentication provider which I found in [this tablist](https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#setting-up-the-provider-examples) and the …

feat: custom payload properties for registration

---

docs/pages/usage.md
src/runtime/types.ts

Hello
A PR as discussed in issue #161 & #189
I have added `Array<string | number | boolean>` to the already existing [NuxtStrapiQueryParams type](https://github.com/nuxt-community/strapi-module/blob/v0-support/src/runtime/types.ts#L5).
This is to ensure that update and create requests can handle more complex data, such as an array of user ids.
Furthermore, I have added custom properties to the registration type and made the username optional.
Strapi 3 also [supports these custom properties](https://github.com/strapi/strapi/blob/releases/v3.6.9/packages/strapi-plugin-users-permissions/controllers/Auth.js#L403). Only the ciritcal properties `['confirmed', 'confirmationToken', 'resetPasswordToken']` are omitted.
This is to reflect the changes made in v1 of this module. (#218)
Updated the …

chore: add array types to NuxtStrapiQueryParams for more complex payloads

---

src/runtime/composables/useStrapiClient.ts

Update the returned error value.  See https://github.com/unjs/ohmyfetch/#%EF%B8%8F-handling-errors
Resolves #220

fix(client): Update returned error

---

docs/pages/4.advanced.md
example/nuxt.config.ts
example/pages/index.vue
src/module.ts
src/runtime/composables/useStrapiGraphQL.ts
src/runtime/composables/useStrapiToken.ts
src/runtime/composables/useStrapiUrl.ts
src/runtime/composables/useStrapiVersion.ts

This allows server-side requests to make use of a separate URL by making full use of runtimeConfig in Nuxt. For instance, I may access a locally-running Strapi instance server-side at http://strapi-instance:1337 while client-side I would use https://strapi.example.com.
This is a functionality that has been very helpful in containerized environments, provided as an [option by modules like nuxt/axios in Nuxt2](https://axios.nuxtjs.org/options#browserbaseurl).
I was unable to find tests within the repository.

feat(module): support server-specific runtime configuration

---

docs/content/2.setup.md
docs/content/3.usage.md
docs/content/4.advanced.md
docs/yarn.lock
src/module.ts
src/runtime/composables/useStrapiAuth.ts

Since Strapi https://github.com/strapi/strapi/releases/tag/v4.2.2 release including pull request https://github.com/strapi/strapi/pull/13435 which resolved issue https://github.com/strapi/strapi/issues/13296, we can now pass the `populate` options to `/users/me`.
So, instead of overriding the API as described here https://strapi.nuxtjs.org/advanced#override-strapi-usersme-route to populate data in `/users/me`, we can now use `auth.populate` option.

feat(module): add `auth.populate` option for `fetchUser`

---

docs/content/2.setup.md
example/nuxt.config.ts
src/module.ts
src/runtime/composables/useStrapiToken.ts

With this PR #262 can be closed, now the cookie name is configurable. Default is `strapi_jwt`

feat: make cookie name configurable

---

docs/content/3.usage.md
docs/content/4.advanced.md
src/module.ts
src/runtime/composables-v3/useStrapi.ts
src/runtime/composables-v3/useStrapi3.ts
src/runtime/composables-v4/useStrapi.ts
src/runtime/composables-v4/useStrapi4.ts
src/runtime/types/v4.d.ts

This PR aims to fix broken types without introducing breaking changes.
See: 
- https://github.com/nuxt-modules/strapi/issues/268
- https://github.com/nuxt-modules/strapi/issues/274
To summarise the type issues:
- single/multiple return requests have ambiguous types
- it's not possible to type the update / create functions without an error
To fix the types without breaking anything, I've introduced a new composable `useStrapi` which is a simple wrapper to the existing v3 or v4 client, depending on which version is being used, with the correct types.
The types for the client allow a user to either set a default type for all requests from the composable `useStrapi<MyData>` and / or override the single data return types from the functions `find<Book>('book')`
`useStrapi3` and `useStrapi4` are …

feat: add `useStrapi` composable with correct types

---

docs/content/3.usage.md
src/runtime/composables/useStrapiMedia.ts

By default, for local provider Strapi endpoints return an media URL in the form `/uploads/image-[hash].png`. 
This is bit problematic and require assign two variables or custom composable to get full url to `<img` tag.
So I add to the repository appropriate composable that can be used in the application code without additional manipulation of strings.

feat(composables): add `useStrapiMedia`

---

src/runtime/composables/useStrapiToken.ts

This is just a small change, but it brings the variable naming consistency with how it's called in the `useStrapiClient` composable.

useNuxtApp variable name consistency

---

src/runtime/composables/useStrapiAuth.ts
src/runtime/strapi.plugin.ts

This is a small but important change. This separates the guard logic in the `fetchUser` method so that it maintains the current functionality while allowing the developer to refetch the user data when/if desired.
By putting `if (!user)` around the fetchUser call in the plugin we maintain that it will only be called once when there is no user state. Then, we we leave the `if (token)` within the fetchUser method to maintain security.
Use case:
While building a profile page, I needed to update the user avatar and info. The avatar in particular posed a bigger problem. I needed to refresh the user info after uploading it. However, after banging my head against the wall for a bit while trying to use the `fetchUser` method, I realized the `!user.value` guard in the method meant that it would …

chore(auth): allow user refetch

---

docs/assets/css/main.css
docs/content/3.usage.md
docs/content/5.advanced.md
docs/nuxt.config.ts

Couple small changes:
1. Updated the docs to change use of the deprecated `useStrapi4` composable to `useStrapi`.
2. It seems that tailwind was removed from docus at some point, but was still being used to style the `badge` container(s). It was also used to style `Strapi` in the hero title. I'm not sure if that's still wanted and you might want to change the `.strapi-title` class name or remove that coloring all together. I at least just wanted to bring these style issues to light.

docs: deprecated usage of `useStrapi4` + missing old tailwind classes

---

docs/content/2.setup.md
example/nuxt.config.ts
src/module.ts

When using any node version above 16, the cookie was not being persisted across browser refreshes. Changing "http://localhost:1337" -> "http://127.0.0.1:1337" fixed this issue. Refer to this issue: https://github.com/nuxt-modules/strapi/issues/229
Resolves: #229

chore: change default api url value

---

docs/content/3.usage.md

Fixed code snippets in the documentation where `find` is wrongly imported but `findOne` is actually being used.
Wrong Import

fix(docs): fixed code snippets

---

docs/content/4.auth.md

By using the default cookie configuration {} and not setting a maxAge, the cookie becomes a SessionCookie by default, which is not what most people want when deploying a website! I just added some minimal configuration in the authentication docs.

docs(auth): advise a minimal cookie config

---

src/module.ts

Fixes #379
allows to do:
```typescript
import type { Strapi4RequestParams } from "@nuxtjs/strapi";
const useProducts = (filters: StrapiRequestParams['filters']) => useStrapi(...)
```

fix(module): export runtime types
